spring:
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: request
    cache: false
    #template-loader-path: classpath:/templates/
    settings:
      number_format: 0.##      #解决数值用逗号分开的问题
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/talent?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
  session:
    store-type: none
  devtools:
    restart:
      #热部署生效
      enabled: true
      #classpath目录下的WEB-INF文件夹内容修改不重启
      #exclude: WEB-INF/**
      #设置重启目录
  resources:
    static-locations: classpath:/static/, classpath:/templates/ #很神奇，不加这句的话http://localhost:8080/jianTai/login可以访问，加了.html后缀就访问失败（理论上默认配置了的，不用显式配置）
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB #配置上传文件大小


#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true

#      additional-paths: src/main/java

server:
  port: 7788
  servlet:
    context-path: /talent
    session:
      timeout: 1440 #session过期时间--单位分钟 -- 1天

#  tomcat:
#    accesslog:
#      enabled: true
#      filted-request-entries: #uri匹配模式:0/null-完全匹配;1-前缀匹配;2-后缀匹配;3-正则表达式
#        - uri: /jianTai/user/
#          type: 2
#      pattern:
#         jiantai %u %t "%r" %s %b %D
#    basedir: D:/logs/accesslog.log
mybatis:
  type-aliases-package: com.jiantai.talent.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    ##开启驼峰映射
    map-underscore-to-camel-case: true

#logging:
#  config: classpath:logback-spring.xml

#  file:
#    name: D:/logs/%d{yyyy-MM-dd}.log
